### PR TITLE
Add support for version 2.34 [NOT FOR 1.1.0]

### PR DESCRIPTION
**Pull request by tokland**
Currently, not required by any project. I had the idea to use it in metadata-sync transformations, but currently we use no typing there, it only makes sense when fully typed.

Also: it orders schemas by name, on each generation the order was random and source diffs were useless.

### CODE REVIEW

**Comment by SferaDev** [comment]
I get this warnings building the schemas for ``2.34``:

```
GET https://admin:district@play.dhis2.org/2.34/api/schemas.json?fields=:all,metadata
Unsupported complex type, default to any: org.hisp.dhis.visualization.ReportingParams
Unsupported complex type, default to any: org.hisp.dhis.visualization.Axis
Unsupported complex type, default to any: org.hisp.dhis.visualization.ReportingParams
Unsupported complex type, default to any: org.hisp.dhis.visualization.ReportingParams
Unsupported complex type, default to any: org.hisp.dhis.visualization.Axis
Unsupported complex type, default to any: org.hisp.dhis.visualization.ReportingParams
Written: /home/sfera/workspace/d2-api/src/2.34/schemas.ts
```

**Comment by tokland** [comment]
Done: 8d553fa0. Actually, `interfaceFromClass has a number of a number of non-exposed-in-schema types mapped as `any`. Ideally, we should use the dhis2-core Java source code to extract its components, versioned. Now they are manual and unversioned interfaces in `schemas/base.ts`.

**Comment by tokland** [comment]
Bug detected for 2.33 attritbuteValues, we can fix it here:

`dataSets[0].attributeValues` has type `D2AttributeValueGeneric<D2Attribute>`, should be `D2AttributeValueGeneric<D2Attribute>[]`.

**Comment by adrianq** [comment]
Does this have to do with the MSF bug reported in Vaccination? Anyway, please go ahead with the fix...

**Comment by tokland** [comment]
> Does this have to do with the MSF bug reported in Vaccination? Anyway, please go ahead with the fix...

No, it's purely on the type level, so it's not urgent at all.

**Pull request merged**
