### PR TITLE
[Fix] Filter unary operators

### PR DESCRIPTION
**Pull request by tokland**
Fixes filter operators that have no value, `null`, `!null` and `empty` (see https://docs.dhis2.org/master/en/developer/html/webapi_metadata_object_filter.html)

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland There is no PR nor in project monitoring neither in metadata sync to test this PR, right? @SferaDev any comments?

**Comment by tokland** [comment]
Jorge found this bug. @xurxodev was this enough?

**Comment by xurxodev** [comment]
In the end, the gee app was released using basic get function from d2-api and set manually this filter because it seemed that d2-api was a bit stuck to release a new version the last week and we needed to create a new release of gee the last week. Now there is no PR where we can validate it, @ifoche, have we time to validate this in gee? maybe in the next feedback time?

**Comment by adrianq** [comment]
Ok, no rush on this. We have to release a new version of d2-api for project monitoring on Thursday but I won't merge this PR for now. @ifoche as @tokland needs to work on the minification issue for the GEE project I have asked him to validate this PR. It should take him no more than 15 mins. We plan for this to happen by the beginning of next week. Give us a shout if you prefer not to incorporate this PR!

**Comment by tokland** [comment]
Let's wait for an app to need the feature.

**Comment by tokland** [comment]
I think this PR is useful, I'll be using it on Samaritans projects for a while and remove the draft flag if no problems are detected (code re-checked, should work).

**Pull request merged**
