### PR TITLE
Add endpoint api.email

### PR DESCRIPTION
**Pull request by tokland**
Implements email endpoint.

https://docs.dhis2.org/master/en/developer/html/webapi_email.html

### CODE REVIEW

**Comment by SferaDev** [comment]
LGTM, two minor comments though.

- We should probably add the endpoint to the readme.
- `sendNotification` could probably be renamed to `sendSystemNotification` as it's more explicit.
- Remember that sending email requires an special authority or having ALL. How does the API respond? Should we control that edge case and handle the error somehow?

Also I believe we will implement the messageConversations as part of metadata-synchronization and we might consider reusing a similar approach to this endpoint.

**Comment by tokland** [comment]
> * We should probably add the endpoint to the readme.
Done!

> * `sendNotification` could probably be renamed to `sendSystemNotification` as it's more explicit.

Done!

> * Remember that sending email requires an special authority or having ALL. How does the API respond? Should we control that edge case and handle the error somehow?

Good point, added to the docs. Currently, d2-api is not performing any permission check, it's up to the caller. Here the user would get a 403 and decide what to do.

> Also I believe we will implement the messageConversations as part of metadata-synchronization and we might consider reusing a similar approach to this endpoint.

https://github.com/EyeSeeTea/d2-api/pull/47

**Comment by SferaDev** [comment]
> Good point. Added note about the required rights to the docs. However, d2-api is not performing any permission check whatsoever. It's up to the caller to process the error response (here, a 403).

Yeah, not sure if we should reconsider that at any point, I would find pretty helpful to know during development which errors might throw and being able to detect them and treat them without having to remember every time, buf of course totally unrelated to this PR 😉

**Comment by tokland** [comment]
> I would find pretty helpful to know during development which errors might throw and being able to detect them

Indeed, while time-consuming, with TS we could be doing very cool things like having specifically typed responses, model validations, and so on. There is one step further I do think we should tackle soon: replacing the promise/exception ApiResponse we have now for a real computation task abstraction that types both the data and the error (an "async either").

**Pull request merged**
